-- MySQL Script generated by MySQL Workbench
-- Mon May  3 15:45:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema flightclub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flightclub` ;

-- -----------------------------------------------------
-- Create user
-- -----------------------------------------------------
CREATE USER 'FlighcClubDbUser'@'localhost' IDENTIFIED WITH mysql_native_password AS '***';GRANT USAGE ON *.* TO 'FlighcClubDbUser'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `FlighcClubDbUser\_%`.* TO 'FlighcClubDbUser'@'localhost';GRANT ALL PRIVILEGES ON `flightclub`.* TO 'FlighcClubDbUser'@'localhost';

-- -----------------------------------------------------
-- Schema flightclub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flightclub` DEFAULT CHARACTER SET utf8 ;
USE `flightclub` ;

-- -----------------------------------------------------
-- Table `flightclub`.`tbl_flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightclub`.`tbl_flight` ;

CREATE TABLE IF NOT EXISTS `flightclub`.`tbl_flight` (
  `Id_Flight` INT NOT NULL AUTO_INCREMENT,
  `No_Flight` VARCHAR(45) NOT NULL,
  `Dt_Flight` DATE NOT NULL,
  `Tm_Departure` TIME NOT NULL,
  `Tm_Arrival` TIME NOT NULL,
  `Tm_Engine_On` TIME NULL DEFAULT NULL,
  `Tm_Engine_Off` TIME NULL DEFAULT NULL,
  `Nm_Plane` VARCHAR(45) NOT NULL,
  `No_Plane` VARCHAR(45) NOT NULL,
  `Cd_ICAO_Departure` CHAR(4) NOT NULL,
  `Cd_ICAO_Arrival` CHAR(4) NOT NULL,
  `Cd_Flight_Type` VARCHAR(45) NOT NULL,
  `Cd_Flight_Mode` VARCHAR(45) NOT NULL,
  `Txt_Meteo` TEXT NOT NULL,
  `Nb_Passengers` INT NOT NULL,
  `Txt_Note` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Flight`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `flightclub`.`tbl_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightclub`.`tbl_group` ;

CREATE TABLE IF NOT EXISTS `flightclub`.`tbl_group` (
  `Id_Group` INT NOT NULL AUTO_INCREMENT,
  `Nm_Group` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Group`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `flightclub`.`tbl_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightclub`.`tbl_picture` ;

CREATE TABLE IF NOT EXISTS `flightclub`.`tbl_picture` (
  `Id_Picture` INT NOT NULL AUTO_INCREMENT,
  `Dttm_Picture` DATETIME NOT NULL,
  `Txt_File_Path` VARCHAR(200) NOT NULL,
  `Id_Flight` INT NOT NULL,
  PRIMARY KEY (`Id_Picture`),
  INDEX `fk_tbl_picture_tbl_flight1_idx` (`Id_Flight` ASC),
  CONSTRAINT `fk_tbl_picture_tbl_flight1`
    FOREIGN KEY (`Id_Flight`)
    REFERENCES `flightclub`.`tbl_flight` (`Id_Flight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `flightclub`.`tbl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightclub`.`tbl_user` ;

CREATE TABLE IF NOT EXISTS `flightclub`.`tbl_user` (
  `Id_User` INT NOT NULL AUTO_INCREMENT,
  `Txt_Email` VARCHAR(100) NOT NULL,
  `Txt_Password_Hash` VARCHAR(128) NOT NULL,
  `Txt_Password_Salt` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Id_User`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `flightclub`.`tbl_user-flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightclub`.`tbl_user-flight` ;

CREATE TABLE IF NOT EXISTS `flightclub`.`tbl_user-flight` (
  `Id_User` INT NOT NULL,
  `Id_Flight` INT NOT NULL,
  `Cd_Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Flight`, `Id_User`),
  INDEX `Id_Flight` (`Id_Flight` ASC),
  INDEX `fk_tbl_user-flight_tbl_user1_idx` (`Id_User` ASC),
  CONSTRAINT `tbl_user-flight_ibfk_1`
    FOREIGN KEY (`Id_Flight`)
    REFERENCES `flightclub`.`tbl_flight` (`Id_Flight`),
  CONSTRAINT `fk_tbl_user-flight_tbl_user1`
    FOREIGN KEY (`Id_User`)
    REFERENCES `flightclub`.`tbl_user` (`Id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `flightclub`.`tbl_user-group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightclub`.`tbl_user-group` ;

CREATE TABLE IF NOT EXISTS `flightclub`.`tbl_user-group` (
  `Id_User` INT NOT NULL,
  `Id_Group` INT NOT NULL,
  `Dttm_Invitation` DATETIME,
  `Dttm_Membership` DATETIME,
  PRIMARY KEY (`Id_User`, `Id_Group`),
  INDEX `fk_tbl_user-group_tbl_group1_idx` (`Id_Group` ASC),
  CONSTRAINT `tbl_user-group_ibfk_1`
    FOREIGN KEY (`Id_User`)
    REFERENCES `flightclub`.`tbl_user` (`Id_User`),
  CONSTRAINT `fk_tbl_user-group_tbl_group1`
    FOREIGN KEY (`Id_Group`)
    REFERENCES `flightclub`.`tbl_group` (`Id_Group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
